// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BreakpointsPerBranch
{
    internal sealed partial class Vsix
    {
        public const string Id = "BreakpointsPerBranch.067a758d-b992-4771-b616-b057a282a5e1";
        public const string Name = "BreakpointsPerBranch";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Will Fuqua";
        public const string Tags = "";
    }
}
